### ISSUE TITLE
Mongodb not working

### ISSUE THREAD

**Issue by Mukunya** [riskawarrior/Mjolnir-Authentication-Server#12]
Ok, so I set the server up the way it's in the documentation. I managed to get the server working with defining users in file _( I removed the error throw code from the mongodb module ). Without the modification, I get this error, I believe it's not a problem with my stuff.

```
---- Mjolnir authentication server (auth) ----
(node:1365) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-11-28 14:20:38\| apiserver is listening...
2020-11-28 14:20:38\| authserver is listening...
2020-11-28 14:20:38\| sessionserver is listening...
/vercel/workpath0/node_modules/mongodb/lib/topologies/replset.js:339
throw err;
^
TypeError: db.collection is not a function
at /vercel/workpath0/lib/driver/mongodb.js:12:16
at /vercel/workpath0/node_modules/mongodb/lib/utils.js:677:5
at /vercel/workpath0/node_modules/mongodb/lib/mongo_client.js:226:7
at connectCallback (/vercel/workpath0/node_modules/mongodb/lib/operations/connect.js:366:5)
at /vercel/workpath0/node_modules/mongodb/lib/operations/connect.js:602:5
at ReplSet.connectHandler (/vercel/workpath0/node_modules/mongodb/lib/topologies/replset.js:336:9)
at Object.onceWrapper (events.js:421:26)
at ReplSet.emit (events.js:314:20)
at /vercel/workpath0/node_modules/mongodb/lib/core/topologies/replset.js:796:18
at processTicksAndRejections (internal/process/task_queues.js:79:11)
Error: Command "node app.js" exited with 1
```

**Comment by Mukunya** [comment]
btw the patched stuff just doesn't work, I had to make my own client, server, hosts file, everything,
